import React from "react";
export default function Posts() {
  return (
    <div>
      <h1>Posts</h1>
      <h1>Posts</h1>
      <h1>Posts</h1>
      <h1>Posts</h1>
      <h1>Posts</h1>
      <h1>Posts</h1>
      <h1>Posts</h1>
      <h1>Posts</h1>
      <h1>Posts</h1>
      <h1>Posts</h1>
      <h1>Posts</h1>
      <h1>Posts</h1>
      <h1>Posts</h1>
      <h1>Posts</h1>
      <h1>Posts</h1>
      <h1>Posts</h1>
      <h1>Posts</h1>
      <h1>Posts</h1>
      <h1>Posts</h1>
      <h1>Posts</h1>
      <h1>Posts</h1>
      <h1>Posts</h1>
      <h1>Posts</h1>
      <h1>Posts</h1>
      <h1>Posts</h1>
      <h1>Posts</h1>
      <h1>Posts</h1>
      <h1>Posts</h1>
      <h1>Posts</h1>
      <h1>Posts</h1>
      <h1>Posts</h1>
      <h1>Posts</h1>
      <h1>Posts</h1>
      <h1>Posts</h1>
      <h1>Posts</h1>
      <h1>Posts</h1>
      <h1>Posts</h1>
      <h1>Posts</h1>
      <h1>Posts</h1>
      <h1>Posts</h1>
      <h1>Posts</h1>
      <h1>Posts</h1>
      <h1>Posts</h1>
      <h1>Posts</h1>
      <h1>Posts</h1>
      <h1>Posts</h1>
      <h1>Posts</h1>
      <h1>Posts</h1>
    </div>
  );
}
